# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Pack project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nuget'
    majorVersion: 1
    minorVersion: 1
    patchVersion: 0
    versioningScheme: byPrereleaseNumber
- task: NuGetCommand@2
  displayName: 'Publish nuget'
  inputs:
    command: 'push'
    allowPackageConflicts: true
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'ClubNatacion/Default/@Prerelease'
